class Constants:
    WINDOW_GUI_ACTIVATE = True
    WINDOW_SIZE = 800 # minimum 800
    FRAMES_PER_SECOND = 24

    ALARM_SYSTEM_ACTIVATE = True


    EYE_ANALYSIS_ON = True
    EYE_AR_THRESHOLD = 0.30
    EYE_CLOSE_SECONDS = 3
    EYE_CLOSE_CONSECUTIVE_FRAMES_THRESHOLD = EYE_CLOSE_SECONDS * FRAMES_PER_SECOND

    MOUTH_ANALYSIS_ON = True
    MOUTH_AR_THRESHOLD = 0.30
    MOUTH_OPEN_SECONDS = 3
    MOUTH_YAWN_PER_MINUTE_THRESHOLD = 3
    MOUTH_OPEN_CONSECUTIVE_FRAMES_THRESHOLD = MOUTH_OPEN_SECONDS * FRAMES_PER_SECOND


